# SIFT:
# nfeatures         --> Maximum number of features to retain
# nOctaveLayers     --> Number of layers in each octave of the image pyramid / each octave downsamples the prior image by half e.g. 512 x 512 --> 256 x 256 / blur increase @ each layer
# contrastThreshold --> Filters out low-contrast features
# edgeThreshold     --> Filters out edge-like features
# sigma             --> Std of the gaussian noise. The higher the values the smoother the image

# ORB :
# nfeatures         --> Maximum number of features to retain
# scale factor      --> Pyramid decemation retion between levels in the image pyramid 
# nLevels           --> Number of intermediate layers (scales) within each octave
# firstlevel        --> The starting pyramid level for keypoint detection
# WTA_K             --> Number of points used to compute BRIEF descriptor
# patchsize         --> Size of the patch around each keypoint used to compute the descriptor
# fastThreshold     --> Threshold for the FAST keypoint detector used in ORB / lower values detect more features but may include noise Source: CHATGPT
# sigma             --> Std of the gaussian noise. The higher the values the smoother the image

#Change this to the path of the dataset
root : '/Users/moezrashed/Documents/Programming/Python/VisualOdometryPipeline/ui_cd_s'

feature_extractor:
  type: SIFT  # Options: SIFT, ORB
  ORB:
    nfeatures: 1000
    scaleFactor: 1.2
    nLevels: 8
    edgeThreshold: 31
    firstLevel: 0
    WTA_K: 2
    patchSize: 31
    fastThreshold: 20
  SIFT:
    nfeatures: 1500
    nOctaveLayers: 3
    contrastThreshold: 0.04
    edgeThreshold: 10
    sigma: 1.9
  scaleFactor: 0.25
  
matcher:
  type: BF  # Options: BF, FLANN
  BF:
    HAMMING: false #false when using SIFT
    cross_check: true
  FLANN:
    algorithm: 1  
    kdTrees: 5
    searchChecks: 50
  strategy:
    use_knn: true 
    k: 2
    ratio: 0.75
    distance_thresh: 30 # Standard matching
 